// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TrackUrTrailer.iOS
{
	public partial class DeliveryListViewController : UIViewController
	{
		public DeliveryListViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
