// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using TrackUrTrailer.Standard;
using System.Collections.ObjectModel;
using MapKit;
using CoreLocation;
using System.Linq;

namespace TrackUrTrailer.iOS
{
    public partial class MapViewController : UIViewController
    {
        private MapViewModel viewModel;
        private ObservableCollection<IMapAnnotation> annotations => viewModel.Annotations;

        public MapViewController(IntPtr handle) : base(handle)
        {
            viewModel = new MapViewModel();
        }

        public override async void ViewDidLoad()
        {
            base.ViewDidLoad();

            await viewModel.GetData();

            AnnotateMap();
            CenterMap();
        }

        public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
        {
            base.PrepareForSegue(segue, sender);

            switch (sender)
            {
                case UITabBarController tabBarController:
                //todo: probably list all orders relevant to this user?
                case UINavigationController navController:
                //tood: probably list the order and direction of this user
                default:
                    break;
            }
        }

        private void CenterMap()
        {
            var centeringCords = (TUTMapAnnotation)annotations.FirstOrDefault();
            var coordinate = centeringCords.Coordinate;

            var span = new MKCoordinateSpan(Help.Map.MilesToLatitudeDegrees(2),
                                            Help.Map.MilesToLongitudeDegrees(2, coordinate.Latitude));

            Map.Region = new MKCoordinateRegion(coordinate, span);
        }

        private void AnnotateMap()
        {
            foreach (TUTMapAnnotation annotation in annotations)
            {
                Map.AddAnnotation(annotation);
            }
        }
    }
}
