// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Linq;
using System.Threading.Tasks;

using TrackUrTrailer.Standard;

namespace TrackUrTrailer.iOS
{
    public partial class OrdersViewController : UITableViewController
    {
        IDataStore<TUTOrder> data;

        public OrdersViewController(IntPtr handle) : base(handle)
        {

        }

        public override async void ViewDidLoad()
        {
            base.ViewDidLoad();

            await ConfigureDataStore();
            ConfigureTableView();
        }

        private void ConfigureTableView()
        {
            if (data != null)
            {
                var dataSource = new TUTTableViewDataSource<TUTOrder>(data.GetCachedOrders().ToList());

                this.ordersList.DataSource = dataSource;
                this.ordersList.ReloadData();
            }
        }

        private async Task ConfigureDataStore()
        {
            if (Help.Dependencies.GetInstance<IDataStore<TUTOrder>>() is IDataStore<TUTOrder> dataStore)
            {
                await dataStore.GetOrdersAsync(true);
                this.data = dataStore;
            }
            else
                throw new Exception("Failure: IDataStore<TUTOrder> can't be configured");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            System.Console.WriteLine("disposting");
        }
    }
}
