// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using TrackUrTrailer.Standard;

namespace TrackUrTrailer.iOS
{
    public partial class SignInViewController : UIViewController
    {
        public SignInViewController(IntPtr handle) : base(handle)
        {

        }

        partial void DriverButtonClicked(NSObject sender)
        {
            InitiateLogin(UserRole.Operations);
        }

        partial void OperationsButtonClicked(NSObject sender)
        {
            InitiateLogin(UserRole.Operations);
        }

        partial void CorporateButtonClicked(NSObject sender)
        {
            InitiateLogin(UserRole.Corporate);
        }

        partial void CustomerButtonClicked(NSObject sender)
        {
            InitiateLogin(UserRole.Customer);
        }

        public void InitiateLogin(UserRole role)
        {
            Users.LogUserIn(role);

            string segueId = "";

            switch (role)
            {
                case UserRole.Driver:
                    segueId = "showDeliveryListSegue";
                    break;
                default:
                    segueId = "showMainTabsSegue";
                    break;
            }

            //animate away as needed.
            this.PerformSegue(segueId, this);
        }
    }
}
