// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Runtime.CompilerServices;
using Airbnb.Lottie;
using CoreGraphics;

namespace TrackUrTrailer.iOS
{
    public partial class OrderCellBackground : UIView
    {
        private bool animationAdded = false;

        nfloat margin = 2;
        nfloat radius = 4;

        public OrderCellBackground(IntPtr handle) : base(handle)
        {

        }

        public override void DrawRect(CoreGraphics.CGRect area, UIViewPrintFormatter formatter)
        {
            //var width = area.Width - (margin * 2);
            //var height = area.Height - (margin * 2);

            //var path = new CGPath();

            //path.MoveToPoint(margin + radius, margin);


            //path.

            //draw rectangle

            base.DrawRect(area, formatter);
        }

        public override void LayoutSubviews()
        {
            AddAnimationView();

            base.LayoutSubviews();
        }

        private void AddAnimationView()
        {
            if (!animationAdded)
            {
                var loadingAnimation = LOTAnimationView.AnimationNamed("truckAnimation");
                loadingAnimation.Play();

                this.AddSubview(loadingAnimation);
            }
        }

        protected override void Dispose(bool disposing)
        {
            foreach (var view in Subviews)
            {
                view.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}
